language: python
python:
  - "3.7"
install:
  - pip install setuptools -U
  - pip install -r requirements.txt
  - python setup.py -q install
stages:
  - name: linter
    - pylint setup.py app/ test/ -d R0201

  - name: test
    - pytest