language: python
python:
  - "3.7"
install:
  - pip install setuptools -U
  - pip install -r requirements.txt
  - python setup.py -q install

jobs:
  - stage: linter
    name: "Linter"
    script: pylint setup.py app/ test/ -d R0201

  - stage: test
    name: "Unit tests"
    script: pytest test

  - stage: coverage
    name: "Coverage"
    script: pytest --cov=app/ test/

  - stage: deploy
    name: Deploy in Heroku
    script:
      - gem install dpl