language: python
python:
  - "3.7"
virtualenv:
  system_site_packages: true
install:
  - pip install setuptools -U
  - pip install -r requirements.txt
  - python setup.py -q install
script:
  - pylint setup.py app/ test/
  - pytest